=== CN-xiaoxiao/myrpc/myrpc-framework/myrpc-core/src/main/java/com/xiaoxiao/bulider/xml/myrpc-config.dtd
<!ELEMENT configuration ( port?, appName?, registry?
        ,serializeType?, serializer?
        ,compressType?, compressor?
        ,loadBalancerType?, loadBalancer?
        ,idGenerator?, packageName?)>

        <!ELEMENT port ANY>

        <!ELEMENT appName ANY>

        <!ELEMENT registry EMPTY>
        <!ATTLIST registry
            url CDATA #REQUIRED>

        <!ELEMENT serializeType EMPTY>
        <!ATTLIST serializeType
                type CDATA #REQUIRED>

        <!ELEMENT serializer EMPTY>
        <!ATTLIST serializer
                class CDATA #REQUIRED>

        <!ELEMENT compressType EMPTY>
        <!ATTLIST compressType
                type CDATA #REQUIRED>

        <!ELEMENT compressor EMPTY>
        <!ATTLIST compressor
                class CDATA #REQUIRED>

        <!ELEMENT loadBalancerType EMPTY>
        <!ATTLIST loadBalancerType
                type CDATA #REQUIRED>

        <!ELEMENT loadBalancer EMPTY>
        <!ATTLIST loadBalancer
                class CDATA #REQUIRED>

        <!ELEMENT idGenerator EMPTY>
        <!ATTLIST idGenerator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                machineId CDATA #REQUIRED>

        <!ELEMENT packageName ANY>

=== CN-xiaoxiao/myrpc/demo/myrpc-provider-demo/src/main/resources/myrpc.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "myrpc-config.dtd">

<configuration>
    <port>8093</port>
    <appName>myrpc-default-appName</appName>

    <registry url="zookeeper://127.0.0.1:2181"/>

    <serializeType type="jdk"/>
    <serializer class="com.xiaoxiao.serialize.impl.JdkSerializer"/>

    <compressType type="gzip"/>
    <compressor class="com.xiaoxiao.compress.impl.GzipCompressor"/>

    <loadBalancerType type="minimumResponseTimeLoadBalancer"/>
    <loadBalancer class="com.xiaoxiao.loadbalance.impl.MinimumResponseTimeLoadBalancer"/>

    <idGenerator class="com.xiaoxiao.IdGenerator" dataCenterId="2" machineId="4"/>

    <packageName>com.xiaoxiao</packageName>

</configuration>
